apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: remoteistios.istio.banzaicloud.io
  labels:
    controller-tools.k8s.io: "1.0"
    app.kubernetes.io/name: {{ include "istio-operator.name" . }}
    helm.sh/chart: {{ include "istio-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: operator
spec:
  additionalPrinterColumns:
  - JSONPath: .status.Status
    description: Status of the resource
    name: Status
    type: string
  - JSONPath: .status.ErrorMessage
    description: Error message
    name: Error
    type: string
  - JSONPath: .status.GatewayAddress
    description: Ingress gateways of the resource
    name: Gateways
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: istio.banzaicloud.io
  names:
    kind: RemoteIstio
    plural: remoteistios
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoInjectionNamespaces:
              description: List of namespaces to label with sidecar auto injection
                enabled
              items:
                type: string
              type: array
            citadel:
              description: Citadel configuration options
              properties:
                affinity:
                  type: object
                enabled:
                  type: boolean
                image:
                  type: string
                nodeSelector:
                  type: object
                resources:
                  type: object
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
            enabledServices:
              description: EnabledServices the Istio component services replicated
                to remote side
              items:
                properties:
                  labelSelector:
                    type: string
                  name:
                    type: string
                  podIPs:
                    items:
                      type: string
                    type: array
                  ports:
                    items:
                      type: object
                    type: array
                required:
                - name
                type: object
              type: array
            excludeIPRanges:
              description: ExcludeIPRanges the range where not to capture egress traffic
              type: string
            includeIPRanges:
              description: IncludeIPRanges the range where to capture egress traffic
              type: string
            proxy:
              description: Proxy configuration options
              properties:
                enableCoreDump:
                  description: If set, newly injected sidecars will have core dumps
                    enabled.
                  type: boolean
                image:
                  type: string
                privileged:
                  description: If set to true, istio-proxy container will have privileged
                    securityContext
                  type: boolean
              type: object
            proxyInit:
              description: Proxy Init configuration options
              properties:
                image:
                  type: string
              type: object
            sidecarInjector:
              description: SidecarInjector configuration options
              properties:
                affinity:
                  type: object
                autoInjectionPolicyEnabled:
                  description: This controls the 'policy' in the sidecar injector
                  type: boolean
                enabled:
                  type: boolean
                image:
                  type: string
                initCNIConfiguration:
                  properties:
                    affinity:
                      type: object
                    binDir:
                      description: Must be the same as the environment’s --cni-bin-dir
                        setting (kubelet parameter)
                      type: string
                    confDir:
                      description: Must be the same as the environment’s --cni-conf-dir
                        setting (kubelet parameter)
                      type: string
                    enabled:
                      description: If true, the privileged initContainer istio-init
                        is not needed to perform the traffic redirect settings for
                        the istio-proxy
                      type: boolean
                    excludeNamespaces:
                      description: List of namespaces to exclude from Istio pod check
                      items:
                        type: string
                      type: array
                    image:
                      type: string
                    logLevel:
                      description: Logging level for CNI binary
                      type: string
                  type: object
                nodeSelector:
                  type: object
                replicaCount:
                  format: int32
                  type: integer
                resources:
                  type: object
                rewriteAppHTTPProbe:
                  description: If true, sidecar injector will rewrite PodSpec for
                    liveness health check to redirect request to sidecar. This makes
                    liveness check work even when mTLS is enabled.
                  type: boolean
                tolerations:
                  items:
                    type: object
                  type: array
              type: object
          required:
          - enabledServices
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
