apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if and .Values.prometheusMetrics.enabled (not .Values.prometheusMetrics.authProxy.enabled) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  {{- end }}
  labels:
    {{- include "istio-operator.operatorLabels" . | nindent 4 }}
spec:
  selector:
   {{- include "istio-operator.operatorSelectorLabels" . | nindent 4 }}
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9443
  {{- if and .Values.prometheusMetrics.enabled (not .Values.prometheusMetrics.authProxy.enabled) }}
  - name: metrics
    protocol: TCP
    port: 8080
    targetPort: 8080
  {{- end }}
