{{- if eq .Values.mode "PASSIVE" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name-with-revision" (dict "name" "istio-ca-root-cert-controller" "context" $) }}
  labels:
    cluster-registry.k8s.cisco.com/controller-aggregated: "true"
    release: {{ .Release.Name }}
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - update
    - delete
    - patch
    - get
    - list
    - watch
{{- end }}
