{{- if eq .Values.mode "ACTIVE" }}
apiVersion: clusterregistry.k8s.cisco.com/v1alpha1
kind: ResourceSyncRule
metadata:
  name: {{ include "name-with-revision" (dict "name" "istio.servicemesh.cisco.com/multi-cluster-secret-sink" "context" $) }}
  annotations:
    cluster-registry.k8s.cisco.com/resource-sync-disabled: "true"
  labels:
    release: {{ .Release.Name }}
spec:
  clusterFeatureMatch:
    - featureName: "istio.servicemesh.cisco.com/multi-cluster-secret-source"
      matchLabels:
        istio.io/rev: {{ include "namespaced-revision" . }}
  groupVersionKind:
    kind: Secret
    version: v1
  rules:
  - match:
    - labels:
      - matchLabels:
          istio.io/rev: {{ include "namespaced-revision" . }}
      content:
      - key: type
        value: k8s.cisco.com/istio-reader-secret
    mutations:
      labels:
        add:
          istio/multiCluster: "true"
{{- end }}
