{{- if eq .Values.mode "ACTIVE" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name-with-revision" (dict "name" "istio-custom-resources-controller" "context" $) }}
  labels:
    cluster-registry.k8s.cisco.com/controller-aggregated: "true"
    release: {{ .Release.Name }}
rules:
  - apiGroups:
    - networking.istio.io
    - telemetry.istio.io
    - security.istio.io
    resources: [ "*" ]
    verbs:
    - create
    - update
    - delete
    - patch
    - get
    - list
    - watch
{{- end }}
