apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name-with-revision" (dict "name" "mesh-reader" "context" $) }}
  labels:
    cluster-registry.k8s.cisco.com/reader-aggregated: "true"
    release: {{ .Release.Name }}
rules:
  - apiGroups: ["servicemesh.cisco.com"]
    resources:
    - istiomeshes
    verbs:
    - get
    - list
    - watch
