{{- if eq .Values.mode "PASSIVE" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "name-with-revision" (dict "name" "mesh-controller" "context" $) }}
  labels:
    cluster-registry.k8s.cisco.com/controller-aggregated: "true"
    release: {{ .Release.Name }}
rules:
  - apiGroups: ["servicemesh.cisco.com"]
    resources:
    - istiomeshes
    verbs:
    - create
    - update
    - delete
    - patch
    - get
    - list
    - watch
  - apiGroups: ["servicemesh.cisco.com"]
    resources:
    - istiomeshes/status
    verbs:
    - get
    - update
    - patch
{{- end }}
