apiVersion: clusterregistry.k8s.cisco.com/v1alpha1
kind: ClusterFeature
metadata:
  name: {{ include "name-with-revision" (dict "name" "peeristiocontrolplane" "context" $) }}
  labels:
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
spec:
  featureName: "peeristiocontrolplane"
