# permissions for end users to edit istios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-editor-role
rules:
- apiGroups:
  - istio.banzaicloud.io
  resources:
  - istios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - istio.banzaicloud.io
  resources:
  - istios/status
  verbs:
  - get
