# permissions for end users to edit remoteistios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteistio-editor-role
rules:
- apiGroups:
  - istio.banzaicloud.io
  resources:
  - remoteistios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - istio.banzaicloud.io
  resources:
  - remoteistios/status
  verbs:
  - get
