# permissions for end users to view remoteistios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: remoteistio-viewer-role
rules:
- apiGroups:
  - istio.banzaicloud.io
  resources:
  - remoteistios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - istio.banzaicloud.io
  resources:
  - remoteistios/status
  verbs:
  - get
