{{- define "service" }}
ports:
- name: tcp-status-port
  port: 15021
  protocol: TCP
  targetPort: 15021
{{ if .Values.exposeIstiod }}
- name: tls-istiod
  port: 15012
  protocol: TCP
  targetPort: 15012
{{ end }}
{{ if .Values.exposeWebhook }}
- name: tls-istiodwebhook
  port: 15017
  protocol: TCP
  targetPort: 15017
{{ end }}
{{ if .Values.exposeClusterServices }}
- name: tls
  port: 15443
  protocol: TCP
  targetPort: 15443
{{ end }}
{{- include "toYamlIf" (dict "value" .Values.service.ports) }}
{{- end }}

{{- define "deployment" }}
env:
- name: ISTIO_META_ROUTER_MODE
  value: sni-dnat
- name: ISTIO_META_REQUESTED_NETWORK_VIEW
  value: {{ .Values.network }}
{{- if eq .Values.distribution "cisco" }}
- name: ISTIO_META_LOCAL_ENDPOINTS_ONLY
  value: "true"
{{- end }}
{{- include "toYamlIf" (dict "value" .Values.deployment.env) }}
{{- end }}

apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  name: {{ include "name-with-revision" (dict "name" "istio-meshexpansion" "context" $) }}
  annotations:
    meshgateway.istio.servicemesh.cisco.com/generate-external-service: "true"
  labels:
    istio.io/rev: {{ include "namespaced-revision" . }}
    app: istio-meshexpansion-gateway
{{- include "toYamlIf" (dict "value" .Values.metadata.labels) | indent 4 }}
{{- include "toYamlIf" (dict "value" .Values.metadata.annotations "key" "annotations" "indent" 2) | indent 2 }}
spec:
  istioControlPlane:
    name: {{ .Values.revision }}
    namespace: {{ .Release.Namespace }}
  runAsRoot: {{ .Values.runAsRoot }}
{{- include "toYamlIf" (dict "value" (merge (include "service" . | fromYaml) .Values.service) "key" "service" "indent" 2) | indent 2 }}
{{- include "toYamlIf" (dict "value" (merge (include "deployment" . | fromYaml) .Values.deployment) "key" "deployment" "indent" 2) | indent 2 }}
  type: ingress
