{{- if and (eq .Values.global.mode "ACTIVE") .Values.pilot.autoscaleEnabled .Values.pilot.autoscaleMin .Values.pilot.autoscaleMax }}
apiVersion: {{ ternary "autoscaling/v2" "autoscaling/v2beta2" (.Capabilities.APIVersions.Has "autoscaling/v2") }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
spec:
  maxReplicas: {{ .Values.pilot.autoscaleMax }}
  minReplicas: {{ .Values.pilot.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
          type: Utilization
          averageUtilization: {{ .Values.pilot.cpu.targetAverageUtilization }}
---
{{- end }}
