{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    istio.io/rev: {{ include "namespaced-revision" . }}
    release: {{ .Release.Name }}
    istio: istiod
spec:
  {{- if .Values.global.defaultPodDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.global.defaultPodDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.global.defaultPodDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      app: istiod
      istio.io/rev: {{ include "namespaced-revision" . }}
---
{{- end }}
