apiVersion: v1
kind: Service
metadata:
  name: istiod
  #name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    istio.io/rev: {{ include "namespaced-revision" . }}
    istio: istiod
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 15010
      name: grpc-xds # plaintext
      protocol: TCP
    - port: 15012
      name: https-dns # mTLS with k8s-signed cert
      protocol: TCP
    - port: 443
      name: https-webhook # validation and injection
      targetPort: 15017
      protocol: TCP
    - port: 15014
      name: http-monitoring # prometheus stats
      protocol: TCP
{{- if eq .Values.global.mode "PASSIVE" }}
  clusterIP: None
  clusterIPs:
  - None
{{- else }}
  selector:
    app: istiod
    istio.io/rev: {{ include "namespaced-revision" . }}
{{- end }}
---
