{{- $gateway := .Values.deployment }}
apiVersion: v1
kind: ServiceAccount
{{ include "toYamlIf" (dict "value" .Values.global.imagePullSecrets "key" "imagePullSecrets") }}
metadata:
  name: {{ $gateway.name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "deployment.labels" . | indent 4 }}
