{{- $gateway := .Values.deployment }}
apiVersion: v1
kind: ServiceAccount
{{- if $gateway.imagePullSecrets }}
imagePullSecrets:
{{ toYaml $gateway.imagePullSecrets -}}
{{- end }}
metadata:
  name: {{ $gateway.name }}-service-account
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "deployment.labels" . | indent 4 }}
