# A sample ICP that can be used to test ambient with the
# istio-operator.  Search for Ambient to see key parameters
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioControlPlane
metadata:
  name: icp-v116x-sample
  namespace: istio-system
spec:
  version: 1.16.1
  mode: ACTIVE
  meshID: mesh1
  networkName: network1
  logging:
    level: "default:info"
  mountMtlsCerts: false
  meshExpansion:
    enabled: false
  istiod:
    deployment:
      replicas:
        min: 1
        max: 5
        count: 1
      resources:
        requests:
          cpu: 500m
          memory: 2048Mi
      nodeSelector: {}
      affinity: {}
      tolerations: []
      podMetadata:
        labels: {}
        annotations: {ambient.istio.io/redirection: disabled}
      securityContext: {}
    enableAnalysis: false
    enableStatus: false
    externalIstiod:
      enabled: false
    traceSampling: 1.0
    enableProtocolSniffingOutbound: true
    enableProtocolSniffingInbound: true
    certProvider: ISTIOD
    spiffe:
      operatorEndpoints:
        enabled: false
  proxy:
    privileged: false
    enableCoreDump: false
    logLevel: "WARNING"
    componentLogLevel: "misc:error"
    clusterDomain: "cluster.local"
    holdApplicationUntilProxyStarts: false
    lifecycle: {}
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 2000m
        memory: 1024Mi
    includeIPRanges: "*"
    excludeIPRanges: ""
    excludeInboundPorts: ""
    excludeOutboundPorts: ""
  proxyInit:
    cni:
      enabled: true
      daemonset:
    resources:
      limits:
        cpu: 2000m
        memory: 1024Mi
      requests:
        cpu: 10m
        memory: 10Mi
  telemetryV2:
    enabled: true
  # Ambient notes - Setting this to true is primary trigger
  # Important that the correct istio service name is passed
  # to ztunnel pod - may require manual override.
  ambientTopology: true
  sds:
    tokenAudience: "istio-ca"
  proxyWasm:
    enabled: false
  watchOneNamespace: false
  caAddress: ""
  distribution: "official"
  containerImageConfiguration:
    # Ambient notes - need to use images that include ambient support
    hub: docker.io/istio
    tag: 1.18.0-alpha.0
    imagePullPolicy: IfNotPresent
  httpProxyEnvs:
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
  meshConfig:
    proxyListenPort: 15001
    connectTimeout: 10s
    protocolDetectionTimeout: 5s
    ingressClass: istio
    ingressService: imgw-sample
    ingressControllerMode: STRICT
    ingressSelector: imgw-sample
    enableTracing: false
    accessLogFile: /dev/stdout
    accessLogFormat: ""
    accessLogEncoding: TEXT
    enableEnvoyAccessLogService: false
    disableEnvoyListenerLog: false
    defaultConfig:
      configPath: ./etc/istio/proxy
      binaryPath: /usr/local/bin/envoy
      serviceCluster: istio-proxy
      drainDuration: 45s
      parentShutdownDuration: 60s
      proxyAdminPort: 15000
      controlPlaneAuthPolicy: MUTUAL_TLS
      concurrency: 2
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    enableAutoMtls: true
    trustDomain: cluster.local
    trustDomainAliases: []
    rootNamespace: istio-system
    dnsRefreshRate: 5s
