apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name-with-namespaced-revision" ( dict "name" "istio-cni" "context" $) }}
  labels:
    app: istio-cni
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name-with-namespaced-revision" ( dict "name" "istio-cni" "context" $) }}
subjects:
- kind: ServiceAccount
  name: {{ include "name-with-revision" ( dict "name" "istio-cni" "context" $) }}
  namespace: {{ .Release.Namespace }}
---
{{- if .Values.cni.repair.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name-with-namespaced-revision" ( dict "name" "istio-cni-repair" "context" $) }}
  labels:
    app: istio-cni
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "name-with-revision" ( dict "name" "istio-cni" "context" $) }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name-with-namespaced-revision" ( dict "name" "istio-cni-repair" "context" $) }}
{{- end }}
---
{{- if ne .Values.cni.psp_cluster_role "" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-cni-psp
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-cni
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.cni.psp_cluster_role }}
subjects:
- kind: ServiceAccount
  name: {{ include "name-with-revision" ( dict "name" "istio-cni" "context" $) }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.cni.taint.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name-with-namespaced-revision" ( dict "name" "istio-cni-taint" "context" $) }}
  labels:
    k8s-app: istio-cni-taint
    istio.io/rev: {{ include "namespaced-revision" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "name-with-revision" ( dict "name" "istio-cni" "context" $) }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name-with-namespaced-revision" ( dict "name" "istio-cni-taint" "context" $) }}
{{- end }}
