apiVersion: v1
kind: ServiceAccount
{{ include "toYamlIf" (dict "value" .Values.global.imagePullSecrets "key" "imagePullSecrets") }}
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istio-cni" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-cni
    release: {{ .Release.Name }}
    istio.io/rev: {{ include "namespaced-revision" . }}
