apiVersion: v1
name: istio-meshgateway
version: 0.2.0
tillerVersion: ">=2.7.2"
description: Helm chart for deploying Istio mesh gateways
keywords:
  - istio
  - ingressgateway
  - egressgateway
  - gateways
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
