# permissions for end users to view istiomeshgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiomeshgateway-viewer-role
rules:
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiomeshgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiomeshgateways/status
  verbs:
  - get
