# permissions for end users to view istiomeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiomesh-viewer-role
rules:
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiomeshes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiomeshes/status
  verbs:
  - get
