# permissions for end users to edit istiomeshgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiomeshgateway-editor-role
rules:
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiomeshgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiomeshgateways/status
  verbs:
  - get
