# permissions for end users to view meshgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meshgateway-viewer-role
rules:
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - meshgateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - meshgateways/status
  verbs:
  - get
