apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: multimesh
spec:
  version: "1.9.5"
  global: false
  meshExpansion: true
  meshPolicy:
    mtlsMode: STRICT
  multiMeshExpansion:
    enabled: true
    envoyFilterEnabled: false
    domains:
    - "acme.corp"
  istioCoreDNS:
    enabled: true
  citadel:
    caSecretName: "cacerts"
  imagePullPolicy: Always
  pilot:
    maxReplicas: 1
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      maxReplicas: 1
      enabled: false
    meshExpansion:
      enabled: true
      ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
