apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: multimesh
spec:
  version: "1.1.10"
  autoInjectionNamespaces:
  - "default"
  useMCP: true
  mtls: true
  multiMesh: true
  controlPlaneSecurityEnabled: true
  istioCoreDNS:
    enabled: true
  citadel:
    caSecretName: "cacerts"
  imagePullPolicy: Always
  pilot:
    maxReplicas: 1
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      maxReplicas: 1
      enabled: false
  mixer:
    maxReplicas: 1
