// +build !ignore_autogenerated

/*
Copyright 2019 Banzai Cloud.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseK8sResourceConfiguration) DeepCopyInto(out *BaseK8sResourceConfiguration) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8sResourceConfiguration.
func (in *BaseK8sResourceConfiguration) DeepCopy() *BaseK8sResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(BaseK8sResourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseK8sResourceConfigurationWithHPA) DeepCopyInto(out *BaseK8sResourceConfigurationWithHPA) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithReplicas.DeepCopyInto(&out.BaseK8sResourceConfigurationWithReplicas)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8sResourceConfigurationWithHPA.
func (in *BaseK8sResourceConfigurationWithHPA) DeepCopy() *BaseK8sResourceConfigurationWithHPA {
	if in == nil {
		return nil
	}
	out := new(BaseK8sResourceConfigurationWithHPA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseK8sResourceConfigurationWithHPAWithoutImage) DeepCopyInto(out *BaseK8sResourceConfigurationWithHPAWithoutImage) {
	*out = *in
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8sResourceConfigurationWithHPAWithoutImage.
func (in *BaseK8sResourceConfigurationWithHPAWithoutImage) DeepCopy() *BaseK8sResourceConfigurationWithHPAWithoutImage {
	if in == nil {
		return nil
	}
	out := new(BaseK8sResourceConfigurationWithHPAWithoutImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseK8sResourceConfigurationWithImage) DeepCopyInto(out *BaseK8sResourceConfigurationWithImage) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	in.BaseK8sResourceConfiguration.DeepCopyInto(&out.BaseK8sResourceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8sResourceConfigurationWithImage.
func (in *BaseK8sResourceConfigurationWithImage) DeepCopy() *BaseK8sResourceConfigurationWithImage {
	if in == nil {
		return nil
	}
	out := new(BaseK8sResourceConfigurationWithImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaseK8sResourceConfigurationWithReplicas) DeepCopyInto(out *BaseK8sResourceConfigurationWithReplicas) {
	*out = *in
	if in.ReplicaCount != nil {
		in, out := &in.ReplicaCount, &out.ReplicaCount
		*out = new(int32)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithImage.DeepCopyInto(&out.BaseK8sResourceConfigurationWithImage)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8sResourceConfigurationWithReplicas.
func (in *BaseK8sResourceConfigurationWithReplicas) DeepCopy() *BaseK8sResourceConfigurationWithReplicas {
	if in == nil {
		return nil
	}
	out := new(BaseK8sResourceConfigurationWithReplicas)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CNIRepairConfiguration) DeepCopyInto(out *CNIRepairConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Hub != nil {
		in, out := &in.Hub, &out.Hub
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.LabelPods != nil {
		in, out := &in.LabelPods, &out.LabelPods
		*out = new(bool)
		**out = **in
	}
	if in.DeletePods != nil {
		in, out := &in.DeletePods, &out.DeletePods
		*out = new(bool)
		**out = **in
	}
	if in.InitContainerName != nil {
		in, out := &in.InitContainerName, &out.InitContainerName
		*out = new(string)
		**out = **in
	}
	if in.BrokenPodLabelKey != nil {
		in, out := &in.BrokenPodLabelKey, &out.BrokenPodLabelKey
		*out = new(string)
		**out = **in
	}
	if in.BrokenPodLabelValue != nil {
		in, out := &in.BrokenPodLabelValue, &out.BrokenPodLabelValue
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNIRepairConfiguration.
func (in *CNIRepairConfiguration) DeepCopy() *CNIRepairConfiguration {
	if in == nil {
		return nil
	}
	out := new(CNIRepairConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateConfig) DeepCopyInto(out *CertificateConfig) {
	*out = *in
	if in.SecretName != nil {
		in, out := &in.SecretName, &out.SecretName
		*out = new(string)
		**out = **in
	}
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateConfig.
func (in *CertificateConfig) DeepCopy() *CertificateConfig {
	if in == nil {
		return nil
	}
	out := new(CertificateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CitadelConfiguration) DeepCopyInto(out *CitadelConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithImage.DeepCopyInto(&out.BaseK8sResourceConfigurationWithImage)
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(bool)
		**out = **in
	}
	if in.EnableNamespacesByDefault != nil {
		in, out := &in.EnableNamespacesByDefault, &out.EnableNamespacesByDefault
		*out = new(bool)
		**out = **in
	}
	if in.SDSEnabled != nil {
		in, out := &in.SDSEnabled, &out.SDSEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ListenedNamespaces != nil {
		in, out := &in.ListenedNamespaces, &out.ListenedNamespaces
		*out = new(string)
		**out = **in
	}
	if in.AdditionalContainerArgs != nil {
		in, out := &in.AdditionalContainerArgs, &out.AdditionalContainerArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CitadelConfiguration.
func (in *CitadelConfiguration) DeepCopy() *CitadelConfiguration {
	if in == nil {
		return nil
	}
	out := new(CitadelConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatadogConfiugration) DeepCopyInto(out *DatadogConfiugration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatadogConfiugration.
func (in *DatadogConfiugration) DeepCopy() *DatadogConfiugration {
	if in == nil {
		return nil
	}
	out := new(DatadogConfiugration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyServiceCommonConfiguration) DeepCopyInto(out *EnvoyServiceCommonConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.TLSSettings != nil {
		in, out := &in.TLSSettings, &out.TLSSettings
		*out = new(TLSSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPKeepalive != nil {
		in, out := &in.TCPKeepalive, &out.TCPKeepalive
		*out = new(TCPKeepalive)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyServiceCommonConfiguration.
func (in *EnvoyServiceCommonConfiguration) DeepCopy() *EnvoyServiceCommonConfiguration {
	if in == nil {
		return nil
	}
	out := new(EnvoyServiceCommonConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvoyStatsD) DeepCopyInto(out *EnvoyStatsD) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvoyStatsD.
func (in *EnvoyStatsD) DeepCopy() *EnvoyStatsD {
	if in == nil {
		return nil
	}
	out := new(EnvoyStatsD)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GalleyConfiguration) DeepCopyInto(out *GalleyConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithReplicas.DeepCopyInto(&out.BaseK8sResourceConfigurationWithReplicas)
	if in.ConfigValidation != nil {
		in, out := &in.ConfigValidation, &out.ConfigValidation
		*out = new(bool)
		**out = **in
	}
	if in.EnableServiceDiscovery != nil {
		in, out := &in.EnableServiceDiscovery, &out.EnableServiceDiscovery
		*out = new(bool)
		**out = **in
	}
	if in.EnableAnalysis != nil {
		in, out := &in.EnableAnalysis, &out.EnableAnalysis
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalContainerArgs != nil {
		in, out := &in.AdditionalContainerArgs, &out.AdditionalContainerArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GalleyConfiguration.
func (in *GalleyConfiguration) DeepCopy() *GalleyConfiguration {
	if in == nil {
		return nil
	}
	out := new(GalleyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfiguration) DeepCopyInto(out *GatewayConfiguration) {
	*out = *in
	in.MeshGatewayConfiguration.DeepCopyInto(&out.MeshGatewayConfiguration)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.CreateOnly != nil {
		in, out := &in.CreateOnly, &out.CreateOnly
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfiguration.
func (in *GatewayConfiguration) DeepCopy() *GatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(GatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaySDSConfiguration) DeepCopyInto(out *GatewaySDSConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySDSConfiguration.
func (in *GatewaySDSConfiguration) DeepCopy() *GatewaySDSConfiguration {
	if in == nil {
		return nil
	}
	out := new(GatewaySDSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewaysConfiguration) DeepCopyInto(out *GatewaysConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.IngressConfig.DeepCopyInto(&out.IngressConfig)
	in.EgressConfig.DeepCopyInto(&out.EgressConfig)
	in.K8sIngress.DeepCopyInto(&out.K8sIngress)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaysConfiguration.
func (in *GatewaysConfiguration) DeepCopy() *GatewaysConfiguration {
	if in == nil {
		return nil
	}
	out := new(GatewaysConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitCNIConfiguration) DeepCopyInto(out *InitCNIConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludeNamespaces != nil {
		in, out := &in.ExcludeNamespaces, &out.ExcludeNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Chained != nil {
		in, out := &in.Chained, &out.Chained
		*out = new(bool)
		**out = **in
	}
	in.Repair.DeepCopyInto(&out.Repair)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitCNIConfiguration.
func (in *InitCNIConfiguration) DeepCopy() *InitCNIConfiguration {
	if in == nil {
		return nil
	}
	out := new(InitCNIConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Istio) DeepCopyInto(out *Istio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Istio.
func (in *Istio) DeepCopy() *Istio {
	if in == nil {
		return nil
	}
	out := new(Istio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Istio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioCoreDNS) DeepCopyInto(out *IstioCoreDNS) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithReplicas.DeepCopyInto(&out.BaseK8sResourceConfigurationWithReplicas)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioCoreDNS.
func (in *IstioCoreDNS) DeepCopy() *IstioCoreDNS {
	if in == nil {
		return nil
	}
	out := new(IstioCoreDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioList) DeepCopyInto(out *IstioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Istio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioList.
func (in *IstioList) DeepCopy() *IstioList {
	if in == nil {
		return nil
	}
	out := new(IstioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IstioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioService) DeepCopyInto(out *IstioService) {
	*out = *in
	if in.IPs != nil {
		in, out := &in.IPs, &out.IPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioService.
func (in *IstioService) DeepCopy() *IstioService {
	if in == nil {
		return nil
	}
	out := new(IstioService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioSpec) DeepCopyInto(out *IstioSpec) {
	*out = *in
	in.Logging.DeepCopyInto(&out.Logging)
	out.MeshPolicy = in.MeshPolicy
	if in.MTLS != nil {
		in, out := &in.MTLS, &out.MTLS
		*out = new(bool)
		**out = **in
	}
	if in.AutoMTLS != nil {
		in, out := &in.AutoMTLS, &out.AutoMTLS
		*out = new(bool)
		**out = **in
	}
	if in.AutoInjectionNamespaces != nil {
		in, out := &in.AutoInjectionNamespaces, &out.AutoInjectionNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MountMtlsCerts != nil {
		in, out := &in.MountMtlsCerts, &out.MountMtlsCerts
		*out = new(bool)
		**out = **in
	}
	if in.DefaultResources != nil {
		in, out := &in.DefaultResources, &out.DefaultResources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.SDS.DeepCopyInto(&out.SDS)
	in.Istiod.DeepCopyInto(&out.Istiod)
	in.Pilot.DeepCopyInto(&out.Pilot)
	in.Citadel.DeepCopyInto(&out.Citadel)
	in.Galley.DeepCopyInto(&out.Galley)
	in.Gateways.DeepCopyInto(&out.Gateways)
	in.Mixer.DeepCopyInto(&out.Mixer)
	in.Policy.DeepCopyInto(&out.Policy)
	in.Telemetry.DeepCopyInto(&out.Telemetry)
	in.SidecarInjector.DeepCopyInto(&out.SidecarInjector)
	in.ProxyWasm.DeepCopyInto(&out.ProxyWasm)
	in.NodeAgent.DeepCopyInto(&out.NodeAgent)
	in.Proxy.DeepCopyInto(&out.Proxy)
	out.ProxyInit = in.ProxyInit
	if in.UseMCP != nil {
		in, out := &in.UseMCP, &out.UseMCP
		*out = new(bool)
		**out = **in
	}
	in.DefaultPodDisruptionBudget.DeepCopyInto(&out.DefaultPodDisruptionBudget)
	out.OutboundTrafficPolicy = in.OutboundTrafficPolicy
	in.Tracing.DeepCopyInto(&out.Tracing)
	if in.MeshExpansion != nil {
		in, out := &in.MeshExpansion, &out.MeshExpansion
		*out = new(bool)
		**out = **in
	}
	if in.MultiMesh != nil {
		in, out := &in.MultiMesh, &out.MultiMesh
		*out = new(bool)
		**out = **in
	}
	in.IstioCoreDNS.DeepCopyInto(&out.IstioCoreDNS)
	if in.LocalityLB != nil {
		in, out := &in.LocalityLB, &out.LocalityLB
		*out = new(LocalityLBConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.MixerlessTelemetry != nil {
		in, out := &in.MixerlessTelemetry, &out.MixerlessTelemetry
		*out = new(MixerlessTelemetryConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.meshNetworks != nil {
		in, out := &in.meshNetworks, &out.meshNetworks
		*out = new(MeshNetworks)
		(*in).DeepCopyInto(*out)
	}
	if in.TrustDomainAliases != nil {
		in, out := &in.TrustDomainAliases, &out.TrustDomainAliases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]CertificateConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioSpec.
func (in *IstioSpec) DeepCopy() *IstioSpec {
	if in == nil {
		return nil
	}
	out := new(IstioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioStatus) DeepCopyInto(out *IstioStatus) {
	*out = *in
	if in.GatewayAddress != nil {
		in, out := &in.GatewayAddress, &out.GatewayAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioStatus.
func (in *IstioStatus) DeepCopy() *IstioStatus {
	if in == nil {
		return nil
	}
	out := new(IstioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstiodConfiguration) DeepCopyInto(out *IstiodConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MultiClusterSupport != nil {
		in, out := &in.MultiClusterSupport, &out.MultiClusterSupport
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstiodConfiguration.
func (in *IstiodConfiguration) DeepCopy() *IstiodConfiguration {
	if in == nil {
		return nil
	}
	out := new(IstiodConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sIngressConfiguration) DeepCopyInto(out *K8sIngressConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnableHttps != nil {
		in, out := &in.EnableHttps, &out.EnableHttps
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sIngressConfiguration.
func (in *K8sIngressConfiguration) DeepCopy() *K8sIngressConfiguration {
	if in == nil {
		return nil
	}
	out := new(K8sIngressConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LightstepConfiguration) DeepCopyInto(out *LightstepConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LightstepConfiguration.
func (in *LightstepConfiguration) DeepCopy() *LightstepConfiguration {
	if in == nil {
		return nil
	}
	out := new(LightstepConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLBConfiguration) DeepCopyInto(out *LocalityLBConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Distribute != nil {
		in, out := &in.Distribute, &out.Distribute
		*out = make([]*LocalityLBDistributeConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LocalityLBDistributeConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Failover != nil {
		in, out := &in.Failover, &out.Failover
		*out = make([]*LocalityLBFailoverConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(LocalityLBFailoverConfiguration)
				**out = **in
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLBConfiguration.
func (in *LocalityLBConfiguration) DeepCopy() *LocalityLBConfiguration {
	if in == nil {
		return nil
	}
	out := new(LocalityLBConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLBDistributeConfiguration) DeepCopyInto(out *LocalityLBDistributeConfiguration) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make(map[string]uint32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLBDistributeConfiguration.
func (in *LocalityLBDistributeConfiguration) DeepCopy() *LocalityLBDistributeConfiguration {
	if in == nil {
		return nil
	}
	out := new(LocalityLBDistributeConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalityLBFailoverConfiguration) DeepCopyInto(out *LocalityLBFailoverConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalityLBFailoverConfiguration.
func (in *LocalityLBFailoverConfiguration) DeepCopy() *LocalityLBFailoverConfiguration {
	if in == nil {
		return nil
	}
	out := new(LocalityLBFailoverConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfiguration) DeepCopyInto(out *LoggingConfiguration) {
	*out = *in
	if in.Level != nil {
		in, out := &in.Level, &out.Level
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfiguration.
func (in *LoggingConfiguration) DeepCopy() *LoggingConfiguration {
	if in == nil {
		return nil
	}
	out := new(LoggingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshGateway) DeepCopyInto(out *MeshGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGateway.
func (in *MeshGateway) DeepCopy() *MeshGateway {
	if in == nil {
		return nil
	}
	out := new(MeshGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshGatewayConfiguration) DeepCopyInto(out *MeshGatewayConfiguration) {
	*out = *in
	in.BaseK8sResourceConfigurationWithHPAWithoutImage.DeepCopyInto(&out.BaseK8sResourceConfigurationWithHPAWithoutImage)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceLabels != nil {
		in, out := &in.ServiceLabels, &out.ServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.SDS.DeepCopyInto(&out.SDS)
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RunAsRoot != nil {
		in, out := &in.RunAsRoot, &out.RunAsRoot
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayConfiguration.
func (in *MeshGatewayConfiguration) DeepCopy() *MeshGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshGatewayList) DeepCopyInto(out *MeshGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeshGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayList.
func (in *MeshGatewayList) DeepCopy() *MeshGatewayList {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshGatewaySpec) DeepCopyInto(out *MeshGatewaySpec) {
	*out = *in
	in.MeshGatewayConfiguration.DeepCopyInto(&out.MeshGatewayConfiguration)
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]v1.ServicePort, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewaySpec.
func (in *MeshGatewaySpec) DeepCopy() *MeshGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(MeshGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshGatewayStatus) DeepCopyInto(out *MeshGatewayStatus) {
	*out = *in
	if in.GatewayAddress != nil {
		in, out := &in.GatewayAddress, &out.GatewayAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayStatus.
func (in *MeshGatewayStatus) DeepCopy() *MeshGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshNetwork) DeepCopyInto(out *MeshNetwork) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]MeshNetworkEndpoint, len(*in))
		copy(*out, *in)
	}
	if in.Gateways != nil {
		in, out := &in.Gateways, &out.Gateways
		*out = make([]MeshNetworkGateway, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNetwork.
func (in *MeshNetwork) DeepCopy() *MeshNetwork {
	if in == nil {
		return nil
	}
	out := new(MeshNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshNetworkEndpoint) DeepCopyInto(out *MeshNetworkEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNetworkEndpoint.
func (in *MeshNetworkEndpoint) DeepCopy() *MeshNetworkEndpoint {
	if in == nil {
		return nil
	}
	out := new(MeshNetworkEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshNetworkGateway) DeepCopyInto(out *MeshNetworkGateway) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNetworkGateway.
func (in *MeshNetworkGateway) DeepCopy() *MeshNetworkGateway {
	if in == nil {
		return nil
	}
	out := new(MeshNetworkGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshNetworks) DeepCopyInto(out *MeshNetworks) {
	*out = *in
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make(map[string]MeshNetwork, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshNetworks.
func (in *MeshNetworks) DeepCopy() *MeshNetworks {
	if in == nil {
		return nil
	}
	out := new(MeshNetworks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshPolicyConfiguration) DeepCopyInto(out *MeshPolicyConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshPolicyConfiguration.
func (in *MeshPolicyConfiguration) DeepCopy() *MeshPolicyConfiguration {
	if in == nil {
		return nil
	}
	out := new(MeshPolicyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerConfiguration) DeepCopyInto(out *MixerConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithHPA.DeepCopyInto(&out.BaseK8sResourceConfigurationWithHPA)
	in.PolicyConfigurationSpec.DeepCopyInto(&out.PolicyConfigurationSpec)
	in.TelemetryConfigurationSpec.DeepCopyInto(&out.TelemetryConfigurationSpec)
	if in.MultiClusterSupport != nil {
		in, out := &in.MultiClusterSupport, &out.MultiClusterSupport
		*out = new(bool)
		**out = **in
	}
	if in.StdioAdapterEnabled != nil {
		in, out := &in.StdioAdapterEnabled, &out.StdioAdapterEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalContainerArgs != nil {
		in, out := &in.AdditionalContainerArgs, &out.AdditionalContainerArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerConfiguration.
func (in *MixerConfiguration) DeepCopy() *MixerConfiguration {
	if in == nil {
		return nil
	}
	out := new(MixerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MixerlessTelemetryConfiguration) DeepCopyInto(out *MixerlessTelemetryConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MixerlessTelemetryConfiguration.
func (in *MixerlessTelemetryConfiguration) DeepCopy() *MixerlessTelemetryConfiguration {
	if in == nil {
		return nil
	}
	out := new(MixerlessTelemetryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAgentConfiguration) DeepCopyInto(out *NodeAgentConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithImage.DeepCopyInto(&out.BaseK8sResourceConfigurationWithImage)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAgentConfiguration.
func (in *NodeAgentConfiguration) DeepCopy() *NodeAgentConfiguration {
	if in == nil {
		return nil
	}
	out := new(NodeAgentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundTrafficPolicyConfiguration) DeepCopyInto(out *OutboundTrafficPolicyConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundTrafficPolicyConfiguration.
func (in *OutboundTrafficPolicyConfiguration) DeepCopy() *OutboundTrafficPolicyConfiguration {
	if in == nil {
		return nil
	}
	out := new(OutboundTrafficPolicyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDBConfiguration) DeepCopyInto(out *PDBConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDBConfiguration.
func (in *PDBConfiguration) DeepCopy() *PDBConfiguration {
	if in == nil {
		return nil
	}
	out := new(PDBConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotConfiguration) DeepCopyInto(out *PilotConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithHPA.DeepCopyInto(&out.BaseK8sResourceConfigurationWithHPA)
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(bool)
		**out = **in
	}
	if in.EnableProtocolSniffingOutbound != nil {
		in, out := &in.EnableProtocolSniffingOutbound, &out.EnableProtocolSniffingOutbound
		*out = new(bool)
		**out = **in
	}
	if in.EnableProtocolSniffingInbound != nil {
		in, out := &in.EnableProtocolSniffingInbound, &out.EnableProtocolSniffingInbound
		*out = new(bool)
		**out = **in
	}
	if in.AdditionalContainerArgs != nil {
		in, out := &in.AdditionalContainerArgs, &out.AdditionalContainerArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotConfiguration.
func (in *PilotConfiguration) DeepCopy() *PilotConfiguration {
	if in == nil {
		return nil
	}
	out := new(PilotConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConfiguration) DeepCopyInto(out *PolicyConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithHPA.DeepCopyInto(&out.BaseK8sResourceConfigurationWithHPA)
	in.PolicyConfigurationSpec.DeepCopyInto(&out.PolicyConfigurationSpec)
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConfiguration.
func (in *PolicyConfiguration) DeepCopy() *PolicyConfiguration {
	if in == nil {
		return nil
	}
	out := new(PolicyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyConfigurationSpec) DeepCopyInto(out *PolicyConfigurationSpec) {
	*out = *in
	if in.ChecksEnabled != nil {
		in, out := &in.ChecksEnabled, &out.ChecksEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyConfigurationSpec.
func (in *PolicyConfigurationSpec) DeepCopy() *PolicyConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(PolicyConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfiguration) DeepCopyInto(out *ProxyConfiguration) {
	*out = *in
	if in.AccessLogFile != nil {
		in, out := &in.AccessLogFile, &out.AccessLogFile
		*out = new(string)
		**out = **in
	}
	if in.AccessLogFormat != nil {
		in, out := &in.AccessLogFormat, &out.AccessLogFormat
		*out = new(string)
		**out = **in
	}
	if in.AccessLogEncoding != nil {
		in, out := &in.AccessLogEncoding, &out.AccessLogEncoding
		*out = new(string)
		**out = **in
	}
	if in.EnableCoreDump != nil {
		in, out := &in.EnableCoreDump, &out.EnableCoreDump
		*out = new(bool)
		**out = **in
	}
	in.EnvoyStatsD.DeepCopyInto(&out.EnvoyStatsD)
	in.EnvoyMetricsService.DeepCopyInto(&out.EnvoyMetricsService)
	in.EnvoyAccessLogService.DeepCopyInto(&out.EnvoyAccessLogService)
	if in.ProtocolDetectionTimeout != nil {
		in, out := &in.ProtocolDetectionTimeout, &out.ProtocolDetectionTimeout
		*out = new(string)
		**out = **in
	}
	if in.UseMetadataExchangeFilter != nil {
		in, out := &in.UseMetadataExchangeFilter, &out.UseMetadataExchangeFilter
		*out = new(bool)
		**out = **in
	}
	in.Lifecycle.DeepCopyInto(&out.Lifecycle)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfiguration.
func (in *ProxyConfiguration) DeepCopy() *ProxyConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyInitConfiguration) DeepCopyInto(out *ProxyInitConfiguration) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyInitConfiguration.
func (in *ProxyInitConfiguration) DeepCopy() *ProxyInitConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyInitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyWasmConfiguration) DeepCopyInto(out *ProxyWasmConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyWasmConfiguration.
func (in *ProxyWasmConfiguration) DeepCopy() *ProxyWasmConfiguration {
	if in == nil {
		return nil
	}
	out := new(ProxyWasmConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteIstio) DeepCopyInto(out *RemoteIstio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteIstio.
func (in *RemoteIstio) DeepCopy() *RemoteIstio {
	if in == nil {
		return nil
	}
	out := new(RemoteIstio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteIstio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteIstioList) DeepCopyInto(out *RemoteIstioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemoteIstio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteIstioList.
func (in *RemoteIstioList) DeepCopy() *RemoteIstioList {
	if in == nil {
		return nil
	}
	out := new(RemoteIstioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RemoteIstioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteIstioSpec) DeepCopyInto(out *RemoteIstioSpec) {
	*out = *in
	if in.EnabledServices != nil {
		in, out := &in.EnabledServices, &out.EnabledServices
		*out = make([]IstioService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AutoInjectionNamespaces != nil {
		in, out := &in.AutoInjectionNamespaces, &out.AutoInjectionNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultResources != nil {
		in, out := &in.DefaultResources, &out.DefaultResources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	in.Citadel.DeepCopyInto(&out.Citadel)
	in.SidecarInjector.DeepCopyInto(&out.SidecarInjector)
	in.Proxy.DeepCopyInto(&out.Proxy)
	out.ProxyInit = in.ProxyInit
	in.signCert.DeepCopyInto(&out.signCert)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteIstioSpec.
func (in *RemoteIstioSpec) DeepCopy() *RemoteIstioSpec {
	if in == nil {
		return nil
	}
	out := new(RemoteIstioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteIstioStatus) DeepCopyInto(out *RemoteIstioStatus) {
	*out = *in
	if in.GatewayAddress != nil {
		in, out := &in.GatewayAddress, &out.GatewayAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteIstioStatus.
func (in *RemoteIstioStatus) DeepCopy() *RemoteIstioStatus {
	if in == nil {
		return nil
	}
	out := new(RemoteIstioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SDSConfiguration) DeepCopyInto(out *SDSConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SDSConfiguration.
func (in *SDSConfiguration) DeepCopy() *SDSConfiguration {
	if in == nil {
		return nil
	}
	out := new(SDSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarInjectorConfiguration) DeepCopyInto(out *SidecarInjectorConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithReplicas.DeepCopyInto(&out.BaseK8sResourceConfigurationWithReplicas)
	in.Init.DeepCopyInto(&out.Init)
	in.InitCNIConfiguration.DeepCopyInto(&out.InitCNIConfiguration)
	if in.RewriteAppHTTPProbe != nil {
		in, out := &in.RewriteAppHTTPProbe, &out.RewriteAppHTTPProbe
		*out = new(bool)
		**out = **in
	}
	if in.AutoInjectionPolicyEnabled != nil {
		in, out := &in.AutoInjectionPolicyEnabled, &out.AutoInjectionPolicyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.EnableNamespacesByDefault != nil {
		in, out := &in.EnableNamespacesByDefault, &out.EnableNamespacesByDefault
		*out = new(bool)
		**out = **in
	}
	if in.NeverInjectSelector != nil {
		in, out := &in.NeverInjectSelector, &out.NeverInjectSelector
		*out = make([]metav1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlwaysInjectSelector != nil {
		in, out := &in.AlwaysInjectSelector, &out.AlwaysInjectSelector
		*out = make([]metav1.LabelSelector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InjectedAnnotations != nil {
		in, out := &in.InjectedAnnotations, &out.InjectedAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdditionalContainerArgs != nil {
		in, out := &in.AdditionalContainerArgs, &out.AdditionalContainerArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InjectedContainerAdditionalArgs != nil {
		in, out := &in.InjectedContainerAdditionalArgs, &out.InjectedContainerAdditionalArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InjectedContainerAdditionalEnvVars != nil {
		in, out := &in.InjectedContainerAdditionalEnvVars, &out.InjectedContainerAdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarInjectorConfiguration.
func (in *SidecarInjectorConfiguration) DeepCopy() *SidecarInjectorConfiguration {
	if in == nil {
		return nil
	}
	out := new(SidecarInjectorConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SidecarInjectorInitConfiguration) DeepCopyInto(out *SidecarInjectorInitConfiguration) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SidecarInjectorInitConfiguration.
func (in *SidecarInjectorInitConfiguration) DeepCopy() *SidecarInjectorInitConfiguration {
	if in == nil {
		return nil
	}
	out := new(SidecarInjectorInitConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignCert) DeepCopyInto(out *SignCert) {
	*out = *in
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Root != nil {
		in, out := &in.Root, &out.Root
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.Chain != nil {
		in, out := &in.Chain, &out.Chain
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignCert.
func (in *SignCert) DeepCopy() *SignCert {
	if in == nil {
		return nil
	}
	out := new(SignCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StrackdriverConfiguration) DeepCopyInto(out *StrackdriverConfiguration) {
	*out = *in
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.MaxNumberOfAttributes != nil {
		in, out := &in.MaxNumberOfAttributes, &out.MaxNumberOfAttributes
		*out = new(int32)
		**out = **in
	}
	if in.MaxNumberOfAnnotations != nil {
		in, out := &in.MaxNumberOfAnnotations, &out.MaxNumberOfAnnotations
		*out = new(int32)
		**out = **in
	}
	if in.MaxNumberOfMessageEvents != nil {
		in, out := &in.MaxNumberOfMessageEvents, &out.MaxNumberOfMessageEvents
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StrackdriverConfiguration.
func (in *StrackdriverConfiguration) DeepCopy() *StrackdriverConfiguration {
	if in == nil {
		return nil
	}
	out := new(StrackdriverConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPKeepalive) DeepCopyInto(out *TCPKeepalive) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPKeepalive.
func (in *TCPKeepalive) DeepCopy() *TCPKeepalive {
	if in == nil {
		return nil
	}
	out := new(TCPKeepalive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSettings) DeepCopyInto(out *TLSSettings) {
	*out = *in
	if in.SubjectAltNames != nil {
		in, out := &in.SubjectAltNames, &out.SubjectAltNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSettings.
func (in *TLSSettings) DeepCopy() *TLSSettings {
	if in == nil {
		return nil
	}
	out := new(TLSSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfiguration) DeepCopyInto(out *TelemetryConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.BaseK8sResourceConfigurationWithHPA.DeepCopyInto(&out.BaseK8sResourceConfigurationWithHPA)
	in.TelemetryConfigurationSpec.DeepCopyInto(&out.TelemetryConfigurationSpec)
	if in.AdditionalEnvVars != nil {
		in, out := &in.AdditionalEnvVars, &out.AdditionalEnvVars
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfiguration.
func (in *TelemetryConfiguration) DeepCopy() *TelemetryConfiguration {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetryConfigurationSpec) DeepCopyInto(out *TelemetryConfigurationSpec) {
	*out = *in
	if in.ReportBatchMaxEntries != nil {
		in, out := &in.ReportBatchMaxEntries, &out.ReportBatchMaxEntries
		*out = new(int32)
		**out = **in
	}
	if in.ReportBatchMaxTime != nil {
		in, out := &in.ReportBatchMaxTime, &out.ReportBatchMaxTime
		*out = new(string)
		**out = **in
	}
	if in.SessionAffinityEnabled != nil {
		in, out := &in.SessionAffinityEnabled, &out.SessionAffinityEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetryConfigurationSpec.
func (in *TelemetryConfigurationSpec) DeepCopy() *TelemetryConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(TelemetryConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingConfiguration) DeepCopyInto(out *TracingConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	in.Zipkin.DeepCopyInto(&out.Zipkin)
	out.Lightstep = in.Lightstep
	out.Datadog = in.Datadog
	in.Strackdriver.DeepCopyInto(&out.Strackdriver)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingConfiguration.
func (in *TracingConfiguration) DeepCopy() *TracingConfiguration {
	if in == nil {
		return nil
	}
	out := new(TracingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZipkinConfiguration) DeepCopyInto(out *ZipkinConfiguration) {
	*out = *in
	if in.TLSSettings != nil {
		in, out := &in.TLSSettings, &out.TLSSettings
		*out = new(TLSSettings)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZipkinConfiguration.
func (in *ZipkinConfiguration) DeepCopy() *ZipkinConfiguration {
	if in == nil {
		return nil
	}
	out := new(ZipkinConfiguration)
	in.DeepCopyInto(out)
	return out
}
