// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package options

import (
	jsonpb "github.com/golang/protobuf/jsonpb"
)

var (
	OptionsMarshaler   = &jsonpb.Marshaler{Int64Uint64asIntegers: true}
	OptionsUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
