{{- if and .Values.deployment.replicas.min .Values.deployment.replicas.max (gt (.Values.deployment.replicas.min | int) 0) (gt (.Values.deployment.replicas.max | int) (.Values.deployment.replicas.min | int)) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istio-sidecar-injector" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "generic.labels" . | indent 4 }}
spec:
  maxReplicas: {{ .Values.deployment.replicas.max }}
  minReplicas: {{ .Values.deployment.replicas.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "name-with-revision" ( dict "name" "istio-sidecar-injector" "context" $) }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.deployment.replicas.targetCPUUtilizationPercentage }}
---
{{- end }}
