apiVersion: v1
kind: ServiceAccount
{{- include "toYamlIf" (dict "value" .Values.global.imagePullSecrets "key" "imagePullSecrets") }}
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istio-sidecar-injector" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "generic.labels" . | indent 4 }}
