// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/common.proto

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	_ "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for NamespacedName
func (this *NamespacedName) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for NamespacedName
func (this *NamespacedName) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BaseK8SResourceConfigurationWithImage
func (this *BaseK8SResourceConfigurationWithImage) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BaseK8SResourceConfigurationWithImage
func (this *BaseK8SResourceConfigurationWithImage) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BaseK8SResourceConfigurationWithReplicas
func (this *BaseK8SResourceConfigurationWithReplicas) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BaseK8SResourceConfigurationWithReplicas
func (this *BaseK8SResourceConfigurationWithReplicas) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BaseK8SResourceConfigurationWithHPA
func (this *BaseK8SResourceConfigurationWithHPA) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BaseK8SResourceConfigurationWithHPA
func (this *BaseK8SResourceConfigurationWithHPA) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BaseK8SResourceConfigurationWithHPAWithoutImage
func (this *BaseK8SResourceConfigurationWithHPAWithoutImage) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BaseK8SResourceConfigurationWithHPAWithoutImage
func (this *BaseK8SResourceConfigurationWithHPAWithoutImage) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for BaseK8SResourceConfiguration
func (this *BaseK8SResourceConfiguration) MarshalJSON() ([]byte, error) {
	str, err := CommonMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for BaseK8SResourceConfiguration
func (this *BaseK8SResourceConfiguration) UnmarshalJSON(b []byte) error {
	return CommonUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	CommonMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	CommonUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{AllowUnknownFields: true}
)
