// Code generated by protoc-gen-deepcopy. DO NOT EDIT.
package v1alpha1

import (
	proto "github.com/golang/protobuf/proto"
)

// DeepCopyInto supports using IstioMeshGatewaySpec within kubernetes types, where deepcopy-gen is used.
func (in *IstioMeshGatewaySpec) DeepCopyInto(out *IstioMeshGatewaySpec) {
	p := proto.Clone(in).(*IstioMeshGatewaySpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioMeshGatewaySpec. Required by controller-gen.
func (in *IstioMeshGatewaySpec) DeepCopy() *IstioMeshGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(IstioMeshGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioMeshGatewaySpec. Required by controller-gen.
func (in *IstioMeshGatewaySpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using Properties within kubernetes types, where deepcopy-gen is used.
func (in *Properties) DeepCopyInto(out *Properties) {
	p := proto.Clone(in).(*Properties)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Properties. Required by controller-gen.
func (in *Properties) DeepCopy() *Properties {
	if in == nil {
		return nil
	}
	out := new(Properties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new Properties. Required by controller-gen.
func (in *Properties) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioMeshGatewayStatus within kubernetes types, where deepcopy-gen is used.
func (in *IstioMeshGatewayStatus) DeepCopyInto(out *IstioMeshGatewayStatus) {
	p := proto.Clone(in).(*IstioMeshGatewayStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioMeshGatewayStatus. Required by controller-gen.
func (in *IstioMeshGatewayStatus) DeepCopy() *IstioMeshGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(IstioMeshGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioMeshGatewayStatus. Required by controller-gen.
func (in *IstioMeshGatewayStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
