// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/istiocontrolplane.proto

// Copyright 2021 Cisco Systems, Inc. and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "istio.io/api/mesh/v1alpha1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using IstioControlPlaneSpec within kubernetes types, where deepcopy-gen is used.
func (in *IstioControlPlaneSpec) DeepCopyInto(out *IstioControlPlaneSpec) {
	p := proto.Clone(in).(*IstioControlPlaneSpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneSpec. Required by controller-gen.
func (in *IstioControlPlaneSpec) DeepCopy() *IstioControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneSpec. Required by controller-gen.
func (in *IstioControlPlaneSpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using IstioControlPlaneStatus within kubernetes types, where deepcopy-gen is used.
func (in *IstioControlPlaneStatus) DeepCopyInto(out *IstioControlPlaneStatus) {
	p := proto.Clone(in).(*IstioControlPlaneStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneStatus. Required by controller-gen.
func (in *IstioControlPlaneStatus) DeepCopy() *IstioControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(IstioControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new IstioControlPlaneStatus. Required by controller-gen.
func (in *IstioControlPlaneStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
