// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/istiomesh.proto

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/api/mesh/v1alpha1"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	_ "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for IstioMeshSpec
func (this *IstioMeshSpec) MarshalJSON() ([]byte, error) {
	str, err := IstiomeshMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioMeshSpec
func (this *IstioMeshSpec) UnmarshalJSON(b []byte) error {
	return IstiomeshUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IstioMeshStatus
func (this *IstioMeshStatus) MarshalJSON() ([]byte, error) {
	str, err := IstiomeshMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioMeshStatus
func (this *IstioMeshStatus) UnmarshalJSON(b []byte) error {
	return IstiomeshUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	IstiomeshMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{Int64Uint64asIntegers: true}
	IstiomeshUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{AllowUnknownFields: true}
)
