// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/istiocontrolplane.proto

// Copyright 2021 Cisco Systems, Inc. and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	bytes "bytes"
	fmt "fmt"
	github_com_gogo_protobuf_jsonpb "github.com/gogo/protobuf/jsonpb"
	proto "github.com/gogo/protobuf/proto"
	_ "istio.io/api/mesh/v1alpha1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// MarshalJSON is a custom marshaler for IstioControlPlaneSpec
func (this *IstioControlPlaneSpec) MarshalJSON() ([]byte, error) {
	str, err := IstiocontrolplaneMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioControlPlaneSpec
func (this *IstioControlPlaneSpec) UnmarshalJSON(b []byte) error {
	return IstiocontrolplaneUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for IstioControlPlaneStatus
func (this *IstioControlPlaneStatus) MarshalJSON() ([]byte, error) {
	str, err := IstiocontrolplaneMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for IstioControlPlaneStatus
func (this *IstioControlPlaneStatus) UnmarshalJSON(b []byte) error {
	return IstiocontrolplaneUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	IstiocontrolplaneMarshaler   = &github_com_gogo_protobuf_jsonpb.Marshaler{}
	IstiocontrolplaneUnmarshaler = &github_com_gogo_protobuf_jsonpb.Unmarshaler{AllowUnknownFields: true}
)
