// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/meshgateway.proto

package v1alpha1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	_ "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using MeshGatewaySpec within kubernetes types, where deepcopy-gen is used.
func (in *MeshGatewaySpec) DeepCopyInto(out *MeshGatewaySpec) {
	p := proto.Clone(in).(*MeshGatewaySpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewaySpec. Required by controller-gen.
func (in *MeshGatewaySpec) DeepCopy() *MeshGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(MeshGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewaySpec. Required by controller-gen.
func (in *MeshGatewaySpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using K8SResourceOverlayPatch within kubernetes types, where deepcopy-gen is used.
func (in *K8SResourceOverlayPatch) DeepCopyInto(out *K8SResourceOverlayPatch) {
	p := proto.Clone(in).(*K8SResourceOverlayPatch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SResourceOverlayPatch. Required by controller-gen.
func (in *K8SResourceOverlayPatch) DeepCopy() *K8SResourceOverlayPatch {
	if in == nil {
		return nil
	}
	out := new(K8SResourceOverlayPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new K8SResourceOverlayPatch. Required by controller-gen.
func (in *K8SResourceOverlayPatch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using K8SResourceOverlayPatch_GroupVersionKind within kubernetes types, where deepcopy-gen is used.
func (in *K8SResourceOverlayPatch_GroupVersionKind) DeepCopyInto(out *K8SResourceOverlayPatch_GroupVersionKind) {
	p := proto.Clone(in).(*K8SResourceOverlayPatch_GroupVersionKind)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SResourceOverlayPatch_GroupVersionKind. Required by controller-gen.
func (in *K8SResourceOverlayPatch_GroupVersionKind) DeepCopy() *K8SResourceOverlayPatch_GroupVersionKind {
	if in == nil {
		return nil
	}
	out := new(K8SResourceOverlayPatch_GroupVersionKind)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new K8SResourceOverlayPatch_GroupVersionKind. Required by controller-gen.
func (in *K8SResourceOverlayPatch_GroupVersionKind) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using K8SResourceOverlayPatch_Patch within kubernetes types, where deepcopy-gen is used.
func (in *K8SResourceOverlayPatch_Patch) DeepCopyInto(out *K8SResourceOverlayPatch_Patch) {
	p := proto.Clone(in).(*K8SResourceOverlayPatch_Patch)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8SResourceOverlayPatch_Patch. Required by controller-gen.
func (in *K8SResourceOverlayPatch_Patch) DeepCopy() *K8SResourceOverlayPatch_Patch {
	if in == nil {
		return nil
	}
	out := new(K8SResourceOverlayPatch_Patch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new K8SResourceOverlayPatch_Patch. Required by controller-gen.
func (in *K8SResourceOverlayPatch_Patch) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MeshGatewayStatus within kubernetes types, where deepcopy-gen is used.
func (in *MeshGatewayStatus) DeepCopyInto(out *MeshGatewayStatus) {
	p := proto.Clone(in).(*MeshGatewayStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayStatus. Required by controller-gen.
func (in *MeshGatewayStatus) DeepCopy() *MeshGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayStatus. Required by controller-gen.
func (in *MeshGatewayStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
