// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1alpha1/meshgateway.proto

package v1alpha1

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "istio.io/api/mesh/v1alpha1"
	_ "istio.io/gogo-genproto/googleapis/google/api"
	_ "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DeepCopyInto supports using MeshGatewaySpec within kubernetes types, where deepcopy-gen is used.
func (in *MeshGatewaySpec) DeepCopyInto(out *MeshGatewaySpec) {
	p := proto.Clone(in).(*MeshGatewaySpec)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewaySpec. Required by controller-gen.
func (in *MeshGatewaySpec) DeepCopy() *MeshGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(MeshGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewaySpec. Required by controller-gen.
func (in *MeshGatewaySpec) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MeshGatewayConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *MeshGatewayConfiguration) DeepCopyInto(out *MeshGatewayConfiguration) {
	p := proto.Clone(in).(*MeshGatewayConfiguration)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayConfiguration. Required by controller-gen.
func (in *MeshGatewayConfiguration) DeepCopy() *MeshGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayConfiguration. Required by controller-gen.
func (in *MeshGatewayConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BaseK8SResourceConfigurationWithHPAWithoutImage within kubernetes types, where deepcopy-gen is used.
func (in *BaseK8SResourceConfigurationWithHPAWithoutImage) DeepCopyInto(out *BaseK8SResourceConfigurationWithHPAWithoutImage) {
	p := proto.Clone(in).(*BaseK8SResourceConfigurationWithHPAWithoutImage)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8SResourceConfigurationWithHPAWithoutImage. Required by controller-gen.
func (in *BaseK8SResourceConfigurationWithHPAWithoutImage) DeepCopy() *BaseK8SResourceConfigurationWithHPAWithoutImage {
	if in == nil {
		return nil
	}
	out := new(BaseK8SResourceConfigurationWithHPAWithoutImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8SResourceConfigurationWithHPAWithoutImage. Required by controller-gen.
func (in *BaseK8SResourceConfigurationWithHPAWithoutImage) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using BaseK8SResourceConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *BaseK8SResourceConfiguration) DeepCopyInto(out *BaseK8SResourceConfiguration) {
	p := proto.Clone(in).(*BaseK8SResourceConfiguration)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8SResourceConfiguration. Required by controller-gen.
func (in *BaseK8SResourceConfiguration) DeepCopy() *BaseK8SResourceConfiguration {
	if in == nil {
		return nil
	}
	out := new(BaseK8SResourceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new BaseK8SResourceConfiguration. Required by controller-gen.
func (in *BaseK8SResourceConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using GatewaySDSConfiguration within kubernetes types, where deepcopy-gen is used.
func (in *GatewaySDSConfiguration) DeepCopyInto(out *GatewaySDSConfiguration) {
	p := proto.Clone(in).(*GatewaySDSConfiguration)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySDSConfiguration. Required by controller-gen.
func (in *GatewaySDSConfiguration) DeepCopy() *GatewaySDSConfiguration {
	if in == nil {
		return nil
	}
	out := new(GatewaySDSConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new GatewaySDSConfiguration. Required by controller-gen.
func (in *GatewaySDSConfiguration) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using ServicePort within kubernetes types, where deepcopy-gen is used.
func (in *ServicePort) DeepCopyInto(out *ServicePort) {
	p := proto.Clone(in).(*ServicePort)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePort. Required by controller-gen.
func (in *ServicePort) DeepCopy() *ServicePort {
	if in == nil {
		return nil
	}
	out := new(ServicePort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new ServicePort. Required by controller-gen.
func (in *ServicePort) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using NamespacedName within kubernetes types, where deepcopy-gen is used.
func (in *NamespacedName) DeepCopyInto(out *NamespacedName) {
	p := proto.Clone(in).(*NamespacedName)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName. Required by controller-gen.
func (in *NamespacedName) DeepCopy() *NamespacedName {
	if in == nil {
		return nil
	}
	out := new(NamespacedName)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new NamespacedName. Required by controller-gen.
func (in *NamespacedName) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}

// DeepCopyInto supports using MeshGatewayStatus within kubernetes types, where deepcopy-gen is used.
func (in *MeshGatewayStatus) DeepCopyInto(out *MeshGatewayStatus) {
	p := proto.Clone(in).(*MeshGatewayStatus)
	*out = *p
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayStatus. Required by controller-gen.
func (in *MeshGatewayStatus) DeepCopy() *MeshGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(MeshGatewayStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInterface is an autogenerated deepcopy function, copying the receiver, creating a new MeshGatewayStatus. Required by controller-gen.
func (in *MeshGatewayStatus) DeepCopyInterface() interface{} {
	return in.DeepCopy()
}
