apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: gateway-multicluster
spec:
  version: "1.7.0-rc.2"
  autoInjectionNamespaces:
  - "default"
  meshPolicy:
    mtlsMode: STRICT
  useMCP: false
  meshExpansion: true
  imagePullPolicy: Always
  pilot:
    maxReplicas: 1
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      maxReplicas: 1
      enabled: false
  mixer:
    maxReplicas: 1
