apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: istio-gw-multi
spec:
  version: "1.9.5"
  global: true
  meshPolicy:
    mtlsMode: STRICT
  meshExpansion: true
  imagePullPolicy: Always
  pilot:
    maxReplicas: 1
  istiod:
    multiClusterSupport: true
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      maxReplicas: 1
      enabled: false
    meshExpansion:
      enabled: true
      ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 8080
