apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp-restricted
rules:
- apiGroups:
  - policy
  resourceNames:
  - istio-operator-psp-restricted
  resources:
  - podsecuritypolicies
  verbs:
  - use
