apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-host
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-host
subjects:
  - kind: ServiceAccount
    name: istio-cni
