apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-restricted
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp-restricted
subjects:
  - kind: ServiceAccount
    name: istio-egressgateway-service-account
  - kind: ServiceAccount
    name: istio-ingressgateway-service-account
  - kind: ServiceAccount
    name: istio-mixer-service-account
  - kind: ServiceAccount
    name: istio-operator-authproxy
  - kind: ServiceAccount
    name: istiod-service-account
  - kind: ServiceAccount
    name: istio-sidecar-injector-service-account
  - kind: ServiceAccount
    name: istiocoredns-service-account
  - kind: ServiceAccount
    name: default
