apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:istio-operator.allow-all
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:istio-operator.allow-all
subjects:
  - kind: ServiceAccount
    name: statefulset-controller
    namespace: kube-system
  - kind: ServiceAccount
    name: replicaset-controller
    namespace: kube-system
