{{- if .Values.global.remotePilotAddress }}
  {{- if not .Values.global.externalIstiod }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod-remote" "context" $) }}
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.global.remotePilotAddress }}
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
  {{- else if regexMatch "^([0-9]*\\.){3}[0-9]*$" .Values.global.remotePilotAddress }}
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod" "context" $) }}
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.global.remotePilotAddress }}
  ports:
  - port: 15012
    name: tcp-istiod
    protocol: TCP
  {{- end }}
---
{{- end }}
