package pilot

import (
	istiov1beta1 "github.com/banzaicloud/istio-operator/pkg/apis/operator/v1beta1"
	"github.com/banzaicloud/istio-operator/pkg/controller/config"
	"github.com/banzaicloud/istio-operator/pkg/k8sutil"
	"github.com/go-logr/logr"
	"github.com/goph/emperror"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

const (
	serviceAccountName     = "istio-pilot-service-account"
	clusterRoleName        = "istio-pilot-cluster-role"
	clusterRoleBindingName = "istio-pilot-cluster-role-binding"
	configMapName          = "istio"
	deploymentName         = "istio-pilot"
	serviceName            = "istio-pilot"
	hpaName                = "istio-pilot-autoscaler"
	gatewayName            = "istio-autogenerated-k8s-ingress"
)

var pilotLabels = map[string]string{
	"app": "istio-pilot",
}

var labelSelector = map[string]string{
	"istio": "pilot",
}

type Reconciler struct {
	config.Reconciler
}

func New(client client.Client, istio *istiov1beta1.Config) *Reconciler {
	return &Reconciler{
		Reconciler: config.Reconciler{
			Client: client,
			Owner:  istio,
		},
	}
}

func (r *Reconciler) Reconcile(log logr.Logger) error {
	for _, res := range []config.Resource{
		r.serviceAccount,
		r.clusterRole,
		r.clusterRoleBinding,
		r.configMap,
		r.deployment,
		r.service,
		r.horizontalPodAutoscaler,
		r.gateway,
	} {
		o := res(r.Owner)
		err := k8sutil.ReconcileResource(log, r.Client, o)
		if err != nil {
			return emperror.WrapWith(err, "failed to reconcile resource", "resource", o.GetObjectKind().GroupVersionKind())
		}
	}
	return nil
}
