apiVersion: v1
name: istiod-remote
version: 1.1.0
tillerVersion: ">=2.7.2"
description: Helm chart for istio control plane configuration for remote clusters
keywords:
  - istio
  - istiod-remote
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/latest/favicons/android-192x192.png
